apiVersion: v1
kind: EcosystemResource
metadata:
  name: neo4j-songs
spec:
  access:
    - role: SONGS_EXPLORER
      grant_type: RESOURCE_USE
    - role: EXTERNAL_APP
      grant_type: RESOURCE_USE
  fqn: Hume.Orchestra.Resource.Neo4j
  parameters:
    - name: host
      value: hume-dev-001.aws.graphaware.com
    - name: port
      value: 7687
    - name: user
      value: songs
    - name: password
      value: ${env:SONGS_NEO4J_DB_PASSWORD}
    - name: database
      value: songs